import Navbar from "@/components/Navbar";
import "./globals.css";

import { Providers } from "./providers";

import type { Metadata } from "next";
import { ReactQueryProvider } from "./reactqueryprovider";

export const metadata: Metadata = {
  title: "Owais Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
